#!/bin/sh
#
# Functions for shell scripting. Should be usable by POSIX sh, bash, and zsh.

# Quick way to run calculations from the prompt
_calc () {
    bc -l <<-END
	scale=10; $@
	END
}

# POSIX-compliant, portable method to check if something is on the path
command_exists() {
    command -v "$1" > /dev/null
}

# POSIX alternative to pgrep
is_running () {
    # shellcheck disable=SC2009
    ps -Aocomm= | grep -q "$@"
}

# Test and source at once
source_if_exists () {
    [ -f "$1" ] && . "$1"
}

# Print git status quicker than ever
git () {
    if [ $# -gt 0 ]; then
        command git "$@"
    else
        command git status --short --branch
    fi
}

# Simple forward-counting timer
stopwatch () {
    trap "echo; trap - INT; return 0" INT
    start=$(date +%s)

    while true; do
        diff=$(($(date +%s) - start))
        # NOTE: we have to trim the trailing decimal point in zsh
        seconds=${diff%.*}
        # NOTE: this relies on the GNU coreutils version of date
        printf "\\r%s" "$(date -u --date @$seconds +%H:%M:%S)"
        sleep 0.2
    done
}

# vim: ts=4
