#!/bin/sh
#
# Functions for shell scripting. Should be usable by POSIX sh, bash, and zsh.

# POSIX-compliant, portable method to check if something is on the path
command_exists() {
    command -v "$1" > /dev/null
}

# POSIX alternative to pgrep
is_running () {
    # shellcheck disable=SC2009
    ps -Aocomm= | grep -q "$@"
}

# Test and source at once
source_if_exists () {
    [ -f "$1" ] && . "$1"
}

# Print git status quicker than ever
git () {
    if [ $# -gt 0 ]; then
        command git "$@"
    else
        command git status --short --branch
    fi
}
