#!/bin/sh
#
# Functions for shell scripting. Should be usable by POSIX sh, bash, and zsh.

# POSIX-compliant, portable method to check if something is on the path
command_exists() {
    command -v "$1" > /dev/null
}

# POSIX alternative to pgrep
is_running () {
    ps -Aocomm= | grep -q "$@"
}
