#!/bin/sh

# Some helper functions
prepend_to_path () {
    if [ -d "$1" ] ; then
        PATH="$1:$PATH"
    fi
}

append_to_path () {
    if [ -d "$1" ] ; then
        PATH="$PATH:$1"
    fi
}

# Add brew coreutils without 'g' prefix
if [ "$OS" = "Darwin" ] ; then
    prepend_to_path "$(brew --prefix)/opt/coreutils/libexec/gnubin"
fi

# Include user's local bin folder(s)
prepend_to_path "$HOME/.local/bin"
prepend_to_path "$HOME/bin"

# Include current dir on PATH
PATH=".:$PATH"

# Include RubyGems bin folder
if command -v gem >/dev/null 2>&1 ; then
    append_to_path "$(ruby -e 'print Gem.user_dir')/bin"
fi

# Ensure RVM is at the end of PATH
append_to_path "$HOME/.rvm/bin"

export PATH

# Add man pages from brew coreutils
if [ "$OS" = "Darwin" ] && [ -d "$(brew --prefix)/opt/coreutils/libexec/gnuman" ] ; then
    MANPATH="$(brew --prefix)/opt/coreutils/libexec/gnuman:$MANPATH"
    export MANPATH
fi
