# Skip this stuff in a login shell, since it will be handled in .profile
if ! [[ -o login ]]; then
    # Include our common environment file
    emulate sh -c "source ~/.env"

    # We want these shared functions for scripting
    emulate sh -c "source $DOTDIR/shell/functions"
fi

# Prevent duplicates in these paths
typeset -U path cdpath fpath manpath
