# Apply base16 colorscheme first
source_if_exists "$DOTDIR/base16/base16-shell/base16-shell.plugin.zsh"

typeset -U config_files
config_files=(~/.dotfiles/zsh/configs/*.zsh)

for file in $config_files; do
    source $file
done

source_if_exists ~/.fzf.zsh

