#!/bin/sh
#
# A setup script to install Homebrew packages, including Homebrew and Homebrew
# Bundle if necessary.

# Load common functions
. ~/.dotfiles/shell/functions

if [ "$OS" != "Darwin" ]; then
    echo "You are not running macOS!"
    exit 0
fi

command_exists ruby || { echo "Ruby is not installed!"; exit 1; }

command_exists brew || {
    # Try to install Homebrew if it's missing
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    command_exists brew || { echo 'Homebrew installation failed!'; exit 1; }
}

brew_bundle_exists() {
    brew commands --quiet | grep '^bundle$'
}

brew_bundle_exists || {
    brew tap Homebrew/bundle
    brew_bundle_exists || { echo 'Homebrew Bundle installation failed!'; exit 1; }
}

brew bundle --file=~/.dotfiles/Brewfile

# Remove old brew versions and cached downloads
brew cleanup
brew cask cleanup --outdated
