#!/bin/sh
#
# A setup script to install python packages.

# Load common functions
. "$DOTDIR/shell/functions"

command_exists python || { echo "Python is not installed!"; exit 1; }

pip_args="install --user --upgrade -r ./pip_requirements.txt"

for pip_cmd in pip3 pip2; do
    command_exists $pip_cmd && $pip_cmd $pip_args
done
