#!/bin/sh
#
# Load zplug installation, if zsh is installed

# Load common functions
. "$DOTDIR/shell/functions"

zplug_install_url="https://raw.githubusercontent.com/zplug/installer/27e930022a6ac91b2b31698991784a30c0663b45/installer.zsh"

command_exists zsh || { echo "Zsh is not installed"; exit 0; }

[ -n "$ZSH_VERSION" ] || {
    echo "Switching to Zsh"
    exec zsh "$DOTDIR/setup/zsh-setup"
}

# This likely isn't interactive zsh, so zplug won't load automatically
source_if_exists "$HOME/.zplug/init.zsh"

command_exists zplug || {
    curl -fsSL --proto-redir -all,https "$zplug_install_url" | zsh
    source_if_exists "$HOME/.zplug/init.zsh"
    command_exists zplug || { echo "Zplug installation failed!"; exit 1; }
}

# Load just our zplug config
source_if_exists "$DOTDIR/zsh/configs/zplug.zsh"

command_exists zplug && {
    zplug check --verbose || zplug install
}
