#! /usr/bin/env bash


# Enable extended completion
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi

    # Do the same for brew-installed completions
    if [ "$OS" = "Darwin" ]; then
        source_if_exists "$(brew --prefix)"/share/bash-completion/bash_completion
    fi
fi

# Git completions
source_if_exists /usr/share/git/completion/git-completion.bash || \
    source_if_exists /usr/local/share/git/completion/git-completion.bash

if command_exists __git_complete; then
    __git_complete g __git_main
else
    echo "Missing git completion"
fi
