#!/bin/bash
#
# Functions exported for use by bash

# Quick way to run calculations from the prompt
= () {
    calc="$@"
    bc -l <<< "scale=10; $calc"
}
declare -fx =

source ~/.dotfiles/shell/functions

# Function exporting only works in Bash
export -f command_exists
export -f is_running
