#!/bin/bash

# Quick way to run calculations from the prompt
= () {
    calc="$@"
    bc -l <<< "scale=10; $calc"
}
declare -fx =

function_exists() {
    declare -f -F $1 > /dev/null
    return $?
}
export -f function_exists

command_exists() {
    # POSIX-compliant, portable method to check if something is on the path
    command -v "$1" &> /dev/null
}
export -f command_exists
