#!/bin/bash
## Prompt setup ##

CMD_SYMBOL=λ
TRIM_DIR_SYMBOL=…

# Generate color variables
# Using tput is more portable than writing the terminal codes directly.
RESET=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
PURPLE=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BOLD=$(tput bold)

# Pull in git functions
source_if_exists /usr/share/git/git-prompt.sh
command_exists __git_ps1 || echo "Missing git prompt functions"

# Export jobs as <running>|<stopped>
function jobscount(){
    stopped_cnt=$(jobs -s | wc -l)
    running_cnt=$(jobs -r | wc -l)
    if [ "$stopped_cnt" -eq 0 ] && [ "$running_cnt" -eq 0 ]; then
        _NUM_JOBS=""
    else
        _NUM_JOBS="$running_cnt|$stopped_cnt "
    fi
    # Clean up temporary variables
    unset stopped_cnt running_cnt
}

# Trim working directory to last 3 dirs
function trim_wd {
    _TRIMMED_PWD=$(echo "${PWD}" | sed "s&${HOME}&~&" | sed "s&.*./\([^/]*/[^/]*/[^/]*\)$&${TRIM_DIR_SYMBOL}/\1&")
}

# Recalculate running jobs and working directory for every prompt
function prompt_command {
    jobscount
    trim_wd

    __git_ps1 "$_PS1_START" "$_PS1_END" "$_PS1_GIT"
}

# Finally, assign PS1 segments (used by git function). Output is:
# - chroot name, if in a chroot
# - Previous exit code, if nonzero
# - Username
# - Shortened working directory
# - Git branch status
# - Number of running and suspended jobs attached to this shell
#
# Colors are wrapped in \[ \] escapes, because they are nonprintable.
# Variables in double quotes are expanded now; single-quoted strings are
# evaluated on every prompt.
_PS1_START="\[$PURPLE\]${CHROOT_NAME:+($CHROOT_NAME) }\[$RED\]"'$([[ $? -eq 0 ]] || echo  "$? ")'"\[$GREEN\]\u \[$BLUE$BOLD\]"'$_TRIMMED_PWD'"\[$RESET\]"
_PS1_GIT=" \[$PURPLE\]⦗\[$RESET\]%s\[$PURPLE\]⦘\[$RESET\]"
_PS1_END=" \[$YELLOW\]"'$_NUM_JOBS'"\[$RESET\]$CMD_SYMBOL "

# Settings for Git prompt
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWCOLORHINTS=1

PROMPT_COMMAND=prompt_command
